import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import vm from "node:vm";
import {fileURLToPath} from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const indexPath=path.join(root,"index.html");
const validSha256s = ["00356c5c6c5c6c407f35fa7fb17db708702e2ed041a55caa6cbc8fb1beeff7fc"];
const html=fs.readFileSync(indexPath,"utf8");
const sha256=crypto.createHash("sha256").update(html).digest("hex");
await import("./presentation-integrity.mjs");
const checks=[];
const check=(name,ok,detail="")=>checks.push({name,ok:Boolean(ok),detail:String(detail)});

check("exact candidate SHA-256",validSha256s.includes(sha256),sha256);
check("document title",html.includes("<title>FE Civil Practice Lab · 4.1.5.51.61 · EXP3.0.2.4.3.48</title>"));
check("APP_VERSION",html.includes('const APP_VERSION = "4.1.5.51.61";'));
check("build label",html.includes('const EXPERIMENTAL_BUILD_LABEL = "Online Experimental EXP3.0.2.4.3.48";'));
check("bulk solution approval and undo",html.includes('data-action="approve-selected-solutions"')&&html.includes('data-action="undo-selected-solution-approvals"')&&html.includes('function solutionQualityReviewIdentity(question)'));
check("combined logo and menu control",html.includes('class="sidebar-collapse-toggle"')&&/sidebar-collapse-toggle[^>]*>[\s\S]*?<img class="sidebar-brand-mark"/.test(html));
check("DB version unchanged",html.includes("const DB_VERSION = 4;"));
check("Gemini fenced JSON delivery",html.includes("Return exactly one fenced json code block and nothing outside it."));
check("manual batch minimal-edit authority",html.includes("function manualQuestionTextBatchMinimalEditSharedAuthority"));
check("generic manual task has confirmed abandon path",html.includes('data-action="show-abandon-manual-batch-task"')&&html.includes('data-action="confirm-abandon-manual-batch-task"')&&html.includes('function confirmAbandonManualBatchTask()'));
check("Question Text task has confirmed abandon path",html.includes('data-action="show-abandon-manual-question-text-batch"')&&html.includes('data-action="confirm-abandon-manual-question-text-batch"')&&html.includes('function confirmAbandonManualQuestionTextBatch()'));
check("guided queues expose explicit abandon controls",html.includes('data-action="end-manual-question-text-queue">Abandon Queue</button>')&&html.includes('data-action="end-manual-bank-diagram-queue" data-diagram-type="${type}">Abandon Queue</button>'));
check("Question Text copy refreshes batch navigation",/async function copyManualQuestionTextBatchPrompt[\s\S]*?await copyText\(batch\.copiedPrompt\);refreshManualSolutionBatchControlsPresentation\(\);toast\(`Copied exact frozen Question Text batch/.test(html));
check("batch navigation shows previous, next, and history",html.includes('data-action="${escapeAttr(navigation.previousAction)}"')&&html.includes('data-action="${escapeAttr(navigation.nextAction)}"')&&html.includes('No Later Batch')&&html.includes('manual-batch-shared-history-region'));
check("manual context follows batch-size edits",html.includes('function refreshManualBatchContextStrip()')&&html.includes('state.manualQuestionTextBatchSetupSize=result.value;refreshManualBatchContextStrip();')&&html.includes('persistManualSolutionBatchSession();refreshManualBatchContextStrip();return;'));
check("batch notices replace the overlay stack",html.includes('className = `manual-batch-inline-toast ${type}`')&&html.includes('notice.__toastTimer = setTimeout(() => notice.remove(), 4300);')&&html.includes('if (title === "AI Batch Tools") $(".toast-stack")?.replaceChildren();'));
check("batch copy message names the selected task",html.includes('manualBatchOperationSetLabel(batch.requestedOperations)')&&!html.includes('frozen manual solution package'));
check("narrow mobile provider links fit as icons",html.includes('.mobile-bar .ai-bookmark-label, .mobile-bar .ai-bookmark-external { display:none; }')&&html.includes('.mobile-bar > strong { flex:1 1 auto; min-width:0;'));
check("dedicated batch UI QA script included",fs.existsSync(path.join(root,'scripts/batch-tools-ui-qa.mjs')));
check("Manual Copy/Paste honors chosen batch size",/function manualBatchEffectiveRoundSize\([^)]*\)\s*\{[\s\S]*?return requestedSize;\s*\}/.test(html)&&html.includes('function manualQuestionTextBatchEffectiveRoundSize(memory) { return memory.batchSize; }'));
check("filter clearing preserves selection",!html.slice(html.indexOf("  function clearAllBankFilters()"),html.indexOf("  function clearBankHiddenFilters()")).includes("ui.selection.clear()"));
check("selection menu stays visible with both select options",html.includes('data-persistent-panel="question-bank-selection-menu"><summary')&&html.includes('data-action="select-all-bank"')&&html.includes('data-action="select-every-bank-question"')&&!html.includes('question-bank-selection-menu"${ui.selection.size ? "" : " hidden"}'));
check("provider links have vector marks",html.includes('function aiBookmarkButtonHTML(target)')&&html.includes('class="ai-bookmark-icon"')&&html.includes('aiBookmarkButtonHTML("gemini")')&&html.includes('aiBookmarkButtonHTML("chatgpt")'));
check("practice origin is shown once in header",html.includes('class="pill green session-source-pill"')&&!html.includes('class="practice-question-origin caption"'));
check("single-row Question Bank marker",html.includes("aligned Question Bank row with visible source filter"));
check("primary Question Bank filters",html.includes('const primaryFilterKeys = bankPrimaryFilterKeys(ui), overflowFilterKeys = bankOverflowFilterKeys(ui);') && html.includes('${primaryFilterMarkup}'));
check("Sources combines origin, upload and bank filters",html.includes('class="shared-filter-popover bank-sources-popover"')&&html.includes('bankFilterControlMarkup("uploadSource",state.bank')&&html.includes('data-source-filter-section="${escapeAttr(group)}"')&&html.includes('bank-sources-membership'));
check("adaptive filter keys and stable relocation",html.includes('Object.freeze(["topic","sources","difficulty","questionType","solutions","solutionOrigin","mathRepair"])')&&html.includes("grid.insertBefore(field,before)")&&html.includes("new ResizeObserver"));
check("compact search and overflow-only More",html.includes("flex:0 0 190px")&&html.includes("details.hidden=!overflow.length")&&html.includes("440 : 260")&&fs.existsSync(path.join(root,"scripts/adaptive-filters-qa.mjs")));
check("unified Solutions and preserved advanced criteria",html.includes('function setBankSolutionMainValue')&&html.includes('id="bank-solution-origin"')&&html.includes('id="bank-solution-math-repair"')&&!html.includes('id="bank-review-status"'));
check("sort beside question list",html.includes('${bankFilterControlMarkup("sort",ui,sourceTypeFilters,sourceOptions)}')&&html.includes('class="bank-table-sort"'));
check("filter cleanup QA included",fs.existsSync(path.join(root,'scripts/filter-cleanup-qa.mjs')));
check("grouped Tools and selection controls",html.includes('bank-toolbar-menu bank-tools-menu')&&html.includes('question-bank-selection-menu"><summary'));
check("search has an explicit submit button and no live filter",html.includes('<button type="submit" class="bank-search-submit-btn"')&&!html.includes('handleBankSearchLiveFilter'));
check("question count in footer",html.includes('class="summary" aria-live="polite">Showing') && !html.includes('class="bank-results-count"'));
check("compact lineage checkboxes",html.includes('.bank-command-surface .shared-filter-options input[type="checkbox"]'));
check("shared motion tokens",html.includes('--motion-standard: 190ms;') && html.includes('@keyframes motion-menu-in'));
check("section-only entrance",html.includes('markMotionView(`section:${state.section}`)') && html.includes('markMotionView("session")'));
check("animated slider fill",html.includes('@property --range-progress') && html.includes('transition:--range-progress var(--motion-fast)'));
check("reduced motion",html.includes('@media (prefers-reduced-motion:reduce)') && html.includes('window.matchMedia("(prefers-reduced-motion: reduce)")'));
check("open picker kept in DOM",html.includes("function renderAppPreservingSharedFilterPanel") && html.includes('staging.innerHTML = target === "bank" ? renderQuestionBank() : renderPractice();') && !html.includes("freshRoot.replaceWith(oldRoot)"));
check("results refresh without menu redraw",html.includes("currentLayout.replaceWith(freshLayout)") && html.includes("currentSummary.replaceWith(freshSummary)"));
check("open filters cannot remain hidden",html.includes("Open filter panels stay visible even if viewport anchoring is interrupted.") && !html.includes('.bank-advanced-filters[open] > .bank-advanced-filter-body:not(.bank-overlay-ready)'));
check("filter ancestors use position-safe fade",html.includes('.bank-advanced-filters[open] > .bank-advanced-filter-body.motion-menu-enter { animation:motion-fade-in') && html.includes('#app.motion-view-enter > .session-shell { animation:motion-fade-in'));
check("long dropdowns fit vertically",html.includes("const preferredTop = below >= placed.height") && html.includes('panel.style.top = `${top - root.top}px`'));
check("compact filter clear has an explicit accessible name",html.includes('bank-toolbar-clear-btn" data-bank-clear-all-filters aria-label="Clear Question Bank filters, search, and sort order"') && html.includes('.bank-toolbar-clear-btn svg')&& html.includes('function updateBankFilterClearPresentation(active)'));
check("dedicated clear selection toolbar control",html.includes('data-action="clear-bank-selected"')&&html.includes('aria-label="Clear selected questions" title="Clear selected questions"')&&html.includes('.bank-toolbar-clear-selection-btn svg'));
check("selection actions share a conditional group",html.includes('class="bank-selection-controls" role="group"')&&html.includes('clearSelected.hidden = !count')&&html.includes('border-left:1px dashed var(--line-strong)'));
check("visual solution legend has hover and pin controls",html.includes('data-solution-indicator-help')&&html.includes('function installSolutionIndicatorHelp()')&&html.includes('solution-indicator-help-dot red'));
check("every manual review can finish",html.includes('function finishManualWholeReview(kind')&&html.includes('footer:manualWholeReviewFooterHTML(kind)')&&html.includes('confirm-finish-manual-whole-review'));
check("flag toggle animation survives rerender",html.includes('flagToggle.classList.toggle("is-active", active)') && html.includes("bankFlagMotionTimer = setTimeout"));
check("sidebar icon rail",html.includes('class="sidebar-collapse-toggle"') && html.includes('sidebar-collapsed') && html.includes('id="primary-sidebar-nav"'));
check("collapsed sidebar hover and keyboard labels",html.includes("function installSidebarButtonTooltips()")&&html.includes("popup.setAttribute('role', 'tooltip')")&&fs.existsSync(path.join(root,"scripts/sidebar-tooltips-qa.mjs")));
check("sidebar preference",html.includes('fepl-sidebar-collapsed-v1') && html.includes('localStorage.setItem(SIDEBAR_COLLAPSED_KEY'));
check("closing motion",html.includes("function animateDismiss") && html.includes("function dismissDetails") && html.includes("closeModal({ animate:true })"));
check("finished exit effects are discarded",html.includes('animation.oncancel = null;') && html.includes('animation.cancel();\n      node.style.pointerEvents = "";'));
check("remaining Question Bank filters",html.includes('<span class="bank-advanced-filter-title">More filters</span>'));
check("combined Practice setup",html.includes('class="groupbox practice-session-card"'));
check("Practice subtopics collapsed by default",html.includes('target === "practice" ? false'));
check("Worksheets sidebar omits portable notice",!html.includes("${portableNotice}"));
check("difficulty responds to card width",html.includes('class="field full difficulty-control"') && html.includes('@container difficulty (min-width:440px)'));
check("difficulty sliders have accessible names",html.includes('aria-label="Minimum difficulty"') && html.includes('aria-label="Maximum difficulty"'));
check("dialog action rows wrap",html.includes('.modal-footer { flex-wrap:wrap; }'));
check("performance charts respond to card width",html.includes('@container performance (min-width:480px)'));
check("default text fields share control styling",html.includes('input:not([type]), input[type="text"]'));
check("no test fixture hook in shipping HTML",!['window.__layoutAudit','window.__studyQA','window.__toolbarQA','window.__tableFit','window.__batchUIQA','window.__reviewQA','window.__solutionQA','window.__bulkSolutionQA','window.__reviewControlsQA','window.__filterQA'].some(hook=>html.includes(hook)));
check("named study presets",html.includes('function studyConfigSnapshot(config)')&&html.includes('function persistStudyPresets(next)'));
check("active filter footer updates in place",html.includes('${bankActiveFiltersMarkup()}')&&html.includes('currentActiveFilters.replaceWith(freshActiveFilters)'));
check("counterfactual no-match guidance",html.includes('function noMatchMarkup(target)')&&html.includes('filteredQuestions(test).length'));
check("separate local recovery database",html.includes('indexedDB.open("FE-Civil-Study-Recovery",1)'));
check("recovery journal validates presentation",html.includes('journal.presentation===JSON.stringify(saved.session.questions.map'));
check("atomic result commit",html.includes('state.db.transaction(["questions","userProgress","sessions","attempts"],"readwrite")'));
check("release QA and screenshot comparison included",fs.existsSync(path.join(root,'scripts/release-qa.mjs'))&&fs.existsSync(path.join(root,'scripts/visual-regression.mjs')));
check("API checkpoints and explicit resume",html.includes("function apiBatchResumeWork()")&&html.includes("apiBatchCheckpointPersist()")&&html.includes('data-action="api-batch-resume-work"'));
check("API saved exit and usage suspension",html.includes("function apiBatchSaveExit()")&&html.includes("function apiBatchAccessIssue(error)")&&html.includes("run.suspendRequested=true"));
check("staged approval and configurable metadata batching",html.includes("function batchApprovalRun(")&&html.includes("data-batch-approval-size")&&html.includes("data-api-batch-request-size")&&html.includes("DB_NAME+'-Batch-Approval'"));
check("no embedded Google API key",!/AIza[0-9A-Za-z_-]{20,}/.test(html));
check("no embedded OpenAI secret key",!/sk-[A-Za-z0-9_-]{20,}/.test(html));

try{
  const start=html.indexOf("<script>(() => {");
  const end=html.indexOf("\n</script>",start);
  if(start<0||end<0)throw new Error("main script block not found");
  new vm.Script(html.slice(start+8,end));
  check("main JavaScript parses",true);
}catch(error){check("main JavaScript parses",false,error.message);}

const failed=checks.filter(item=>!item.ok);
console.log(JSON.stringify({passed:checks.length-failed.length,failed:failed.length,total:checks.length,index_sha256:sha256,checks},null,2));
if(failed.length)process.exit(1);
